Add friends and likes
IT-Egor/java-filmorate pull request #2
Opened 2024-11-13 16:08 UTC by IT-Egor

2024-11-14 11:58 UTC, vlolad requested changes
Привет!

Замечания только по распределению задач между контроллером, сервисом и хранилищем. Основную логику содержит как раз сервис, большую часть задач по валидации и взаимодействию с хранилищем надо перенести в него. В остальном отлично, тесты тоже верно написаны.

Хорошего дня!

2024-11-14 11:58 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmStorage.addFilm(film);
Создание фильма проходит через сервис, контроллер напрямую с хранилищем вообще не взаимодействует (бывают исключения, но не в этом ТЗ)

Чаще всего контроллер отвечает, по большей части, за распределение запросов по сервисам (обрабатывает запрос с первичными проверками, формирует DTO при необходимости и передает сервису). Сервис уже проводит внутренние проверки, включая авторизацию и более глубокую валидацию (например, проверку на существование пользователя в базе), и он же общается с БД через класс-хранилище

2024-11-14 11:58 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmStorage.updateFilm(film);
Тут аналогично

2024-11-14 11:58 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmStorage.addFilm(film);
В ТЗ это раньше более явно было написано, сейчас почему-то только про лайки и популярные фильмы. Но вообще все запросы должны через сервис идти, иначе смысла нет в архитектуре приложения)

2024-11-14 11:58 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        return userStorage.getUsers();
Тут как и с фильмами - запросы через сервис проходят

2024-11-14 11:58 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/model/ErrorResponse.java
> +public class ErrorResponse {
Не обязательно, просто на будущее

Обычно при формировании ответа с ошибкой ещё добавляют поля с timestamp и технической информацией (например, где возникла ошибка). Не уверен, что автотесты в постмане на это расчитаны, так что fyi для будущих проектов)

2024-11-14 11:58 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/InMemoryFilmStorage.java
> +        Validator.validateFilm(film);
Валидацию лучше перенести в сервис. Коммент для всех использований валидатора в хранилищах

2024-11-14 11:58 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/InMemoryFilmStorage.java
> +        Validator.validateFilm(film);
Ну и можешь доработать с валидацией через аннотации, это даже проще (и потом всё равно станет обязательным с:)

2024-11-14 21:32 UTC, IT-Egor commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/InMemoryFilmStorage.java
> +        Validator.validateFilm(film);
Я не смог разобраться, как полностью отказаться от валидатора, поэтому решил ничего не менять. Если конкретнее, то не нашел аннотацию, которая задает проверку минимальной даты в прошлом. Есть PastOrPresent, но она не проверяет на минимальную дату

2024-11-15 06:21 UTC, vlolad approved these changes
Привет!

Всё отлично, принято)

2024-11-23 16:13 UTC, merged